# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.0.84.190:5000/rajdavies/open-liberty
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  name: open-liberty
  type: ClusterIP
  externalPort: 9080
  internalPort: 9080
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
